version: '3.3'

services:
  app:
    build: .
    container_name: python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8088:80
      - 8002:5000
    volumes:
      - .:/code
